version: '3.8'

networks: 
    medproject:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: web-server
        ports: 
            - 80:80
            - 8080:8080
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/common:/etc/nginx/common
            - ./nginx/sites-available:/etc/nginx/sites-available

            # Projects is the base folder. change it to your current dir
            - "${PROJECT_ROOT}:/var/www/html/"
            - "${PROJECT_ROOT}log/:/var/www/html/log/"
        depends_on: 
            - php
        networks: 
            - medproject
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: always
        environment:
          # reference from .env file
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - medproject

    php:
        build:
            args:
                user: "${USER}" # your username on your machine, you can get it by running echo $USER 
            context: ./php/
        container_name: php-fpm
        ports: 
            - "${FPM_PORT}:9000"
        volumes: 
            # Projects is the base folder. change it to your current dir
            - "${PROJECT_ROOT}:/var/www/html/"
            - "${HOME}/temp:${HOME}"
            - "${HOME}/.ssh/:${HOME}/.ssh"
        depends_on:
            - mysql
        networks: 
            - medproject
